export const data = 
[{
  "id": 229,
  "license_plate": "IVVH56",
  "plate_confidence": 91,
  "make": "JEEP",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:11 AM"
}, {
  "id": 481,
  "license_plate": "Y9925",
  "plate_confidence": 90,
  "make": "TOYOTA",
  "color": "BLUE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:42 AM"
}, {
  "id": 167,
  "license_plate": "QDONN",
  "plate_confidence": 94,
  "make": "FORD",
  "color": "RED",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:03 AM"
}, {
  "id": 83,
  "license_plate": "JR3",
  "plate_confidence": 88,
  "make": "BENTLEY",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:53 AM"
}, {
  "id": 87,
  "license_plate": "LFL025",
  "plate_confidence": 91,
  "make": "FORD",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:53 AM"
}, {
  "id": 7,
  "license_plate": "158KN",
  "plate_confidence": 87,
  "make": "MITSUBISHI",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:32 AM"
}, {
  "id": 362,
  "license_plate": "X0",
  "plate_confidence": 82,
  "make": "ALFAROMEO",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:28 AM"
}, {
  "id": 337,
  "license_plate": "AIH1SZ",
  "plate_confidence": 89,
  "make": "FORD",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:24 AM"
}, {
  "id": 394,
  "license_plate": "KKW60",
  "plate_confidence": 85,
  "make": "TOYOTA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:33 AM"
}, {
  "id": 141,
  "license_plate": "AE8F7",
  "plate_confidence": 89,
  "make": "JEEP",
  "color": "RED",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:01 AM"
}, {
  "id": 440,
  "license_plate": "HKD3788",
  "plate_confidence": 93,
  "make": "HYUNDAI",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:38 AM"
}, {
  "id": 137,
  "license_plate": "AS07NI",
  "plate_confidence": 92,
  "make": "CHEVROLET",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:00 AM"
}, {
  "id": 463,
  "license_plate": "NSX8175",
  "plate_confidence": 94,
  "make": "BMW",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:40 AM"
}, {
  "id": 196,
  "license_plate": "NT5M",
  "plate_confidence": 84,
  "make": "HONDA",
  "color": "RED",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:07 AM"
}, {
  "id": 485,
  "license_plate": "3S",
  "plate_confidence": 83,
  "make": "LEXUS",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:42 AM"
}, {
  "id": 162,
  "license_plate": "6K21J8",
  "plate_confidence": 84,
  "make": "NISSAN",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:03 AM"
}, {
  "id": 355,
  "license_plate": "IEZC",
  "plate_confidence": 88,
  "make": "LANDROVER",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:27 AM"
}, {
  "id": 86,
  "license_plate": "AJ12JI",
  "plate_confidence": 95,
  "make": "NISSAN",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:53 AM"
}, {
  "id": 81,
  "license_plate": "Q08",
  "plate_confidence": 82,
  "make": "FORD",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:52 AM"
}, {
  "id": 455,
  "license_plate": "96",
  "plate_confidence": 83,
  "make": "KIA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:40 AM"
}, {
  "id": 29,
  "license_plate": "AS",
  "plate_confidence": 80,
  "make": "FORD",
  "color": "BLUE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:43 AM"
}, {
  "id": 291,
  "license_plate": "KBT9326",
  "plate_confidence": 94,
  "make": "NISSAN",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:18 AM"
}, {
  "id": 250,
  "license_plate": "AI4IE",
  "plate_confidence": 89,
  "make": "MITSUBISHI",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:14 AM"
}, {
  "id": 260,
  "license_plate": "BPP6K",
  "plate_confidence": 95,
  "make": "GMC",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:16 AM"
}, {
  "id": 233,
  "license_plate": "12ZJ",
  "plate_confidence": 87,
  "make": "PORSCHE",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:12 AM"
}, {
  "id": 329,
  "license_plate": "LFW24",
  "plate_confidence": 93,
  "make": "FORD",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:24 AM"
}, {
  "id": 68,
  "license_plate": "21EK",
  "plate_confidence": 90,
  "make": "FORD",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:51 AM"
}, {
  "id": 150,
  "license_plate": "D1RH",
  "plate_confidence": 96,
  "make": "TOYOTA",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:01 AM"
}, {
  "id": 67,
  "license_plate": "CI00785",
  "plate_confidence": 89,
  "make": "DODGE",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:51 AM"
}, {
  "id": 269,
  "license_plate": "CTRT94",
  "plate_confidence": 85,
  "make": "DODGE",
  "color": "BLUE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:16 AM"
}, {
  "id": 241,
  "license_plate": "R480",
  "plate_confidence": 88,
  "make": "KIA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:13 AM"
}, {
  "id": 83,
  "license_plate": "JR3",
  "plate_confidence": 88,
  "make": "BENTLEY",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:53 AM"
}, {
  "id": 368,
  "license_plate": "39LGKD",
  "plate_confidence": 91,
  "make": "HONDA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:28 AM"
}, {
  "id": 221,
  "license_plate": "DC32XK",
  "plate_confidence": 85,
  "make": "NISSAN",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:10 AM"
}, {
  "id": 108,
  "license_plate": "PYSA25",
  "plate_confidence": 95,
  "make": "FORD",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:56 AM"
}, {
  "id": 108,
  "license_plate": "PYSA25",
  "plate_confidence": 95,
  "make": "FORD",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:56 AM"
}, {
  "id": 103,
  "license_plate": "IT08CZ",
  "plate_confidence": 89,
  "make": "LANDROVER",
  "color": "GREEN",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:54 AM"
}, {
  "id": 253,
  "license_plate": "54",
  "plate_confidence": 73,
  "make": "MAZDA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:15 AM"
}, {
  "id": 347,
  "license_plate": "WR0510",
  "plate_confidence": 87,
  "make": "TOYOTA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:26 AM"
}, {
  "id": 494,
  "license_plate": "QCNC10",
  "plate_confidence": 84,
  "make": "LANDROVER",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:44 AM"
}, {
  "id": 86,
  "license_plate": "AJ12JI",
  "plate_confidence": 95,
  "make": "NISSAN",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:53 AM"
}, {
  "id": 13,
  "license_plate": "RC",
  "plate_confidence": 77,
  "make": "TOYOTA",
  "color": "BLUE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:40 AM"
}, {
  "id": 387,
  "license_plate": "228JI",
  "plate_confidence": 90,
  "make": "GMC",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:31 AM"
}, {
  "id": 408,
  "license_plate": "PK0",
  "plate_confidence": 84,
  "make": "CHEVROLET",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:34 AM"
}, {
  "id": 62,
  "license_plate": "13E",
  "plate_confidence": 91,
  "make": "TOYOTA",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:50 AM"
}, {
  "id": 286,
  "license_plate": "NNC646",
  "plate_confidence": 96,
  "make": "MAZDA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:18 AM"
}, {
  "id": 271,
  "license_plate": "HCC38",
  "plate_confidence": 82,
  "make": "HUMMER",
  "color": "RED",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:16 AM"
}, {
  "id": 69,
  "license_plate": "ZBK19",
  "plate_confidence": 88,
  "make": "CHEVROLET",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:51 AM"
}, {
  "id": 119,
  "license_plate": "AH71JY",
  "plate_confidence": 89,
  "make": "JEEP",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:58 AM"
}, {
  "id": 64,
  "license_plate": "Y17HUA",
  "plate_confidence": 94,
  "make": "TOYOTA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:50 AM"
}, {
  "id": 212,
  "license_plate": "KW98",
  "plate_confidence": 85,
  "make": "NISSAN",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:09 AM"
}, {
  "id": 248,
  "license_plate": "KBB",
  "plate_confidence": 82,
  "make": "ALFAROMEO",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:13 AM"
}, {
  "id": 64,
  "license_plate": "Y17HUA",
  "plate_confidence": 94,
  "make": "TOYOTA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:50 AM"
}, {
  "id": 497,
  "license_plate": "N60771",
  "plate_confidence": 92,
  "make": "DODGE",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:44 AM"
}, {
  "id": 323,
  "license_plate": "CG4PY",
  "plate_confidence": 94,
  "make": "HONDA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:22 AM"
}, {
  "id": 35,
  "license_plate": "8V",
  "plate_confidence": 79,
  "make": "VOLKSWAGEN",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:45 AM"
}, {
  "id": 79,
  "license_plate": "IJ97R",
  "plate_confidence": 83,
  "make": "HONDA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:52 AM"
}, {
  "id": 397,
  "license_plate": "LVAA24",
  "plate_confidence": 87,
  "make": "VOLVO",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:33 AM"
}, {
  "id": 96,
  "license_plate": "K61RM",
  "plate_confidence": 93,
  "make": "AUDI",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:54 AM"
}, {
  "id": 317,
  "license_plate": "GT10P",
  "plate_confidence": 88,
  "make": "TOYOTA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:21 AM"
}, {
  "id": 354,
  "license_plate": "DE2PCH",
  "plate_confidence": 83,
  "make": "ISUZU",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:27 AM"
}, {
  "id": 335,
  "license_plate": "YZ006",
  "plate_confidence": 84,
  "make": "KIA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:24 AM"
}, {
  "id": 331,
  "license_plate": "DUB",
  "plate_confidence": 84,
  "make": "LANDROVER",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:24 AM"
}, {
  "id": 195,
  "license_plate": "2B8934",
  "plate_confidence": 88,
  "make": "VOLKSWAGEN",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:07 AM"
}, {
  "id": 197,
  "license_plate": "AK0L5HP",
  "plate_confidence": 89,
  "make": "TOYOTA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:07 AM"
}, {
  "id": 279,
  "license_plate": "EGT822",
  "plate_confidence": 96,
  "make": "NISSAN",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:17 AM"
}, {
  "id": 203,
  "license_plate": "C3RD",
  "plate_confidence": 92,
  "make": "HYUNDAI",
  "color": "BLUE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:09 AM"
}, {
  "id": 36,
  "license_plate": "DU5",
  "plate_confidence": 91,
  "make": "HONDA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:46 AM"
}, {
  "id": 71,
  "license_plate": "31Z",
  "plate_confidence": 79,
  "make": "HONDA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:51 AM"
}, {
  "id": 483,
  "license_plate": "765ECW",
  "plate_confidence": 94,
  "make": "MAZDA",
  "color": "RED",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:42 AM"
}, {
  "id": 109,
  "license_plate": "GX",
  "plate_confidence": 93,
  "make": "VOLVO",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:56 AM"
}, {
  "id": 346,
  "license_plate": "5RLH",
  "plate_confidence": 87,
  "make": "TOYOTA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:26 AM"
}, {
  "id": 234,
  "license_plate": "HNWT3",
  "plate_confidence": 77,
  "make": "HONDA",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:12 AM"
}, {
  "id": 395,
  "license_plate": "88",
  "plate_confidence": 77,
  "make": "HONDA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:33 AM"
}, {
  "id": 257,
  "license_plate": "RMQ664",
  "plate_confidence": 94,
  "make": "MAZDA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:15 AM"
}, {
  "id": 29,
  "license_plate": "AS",
  "plate_confidence": 80,
  "make": "FORD",
  "color": "BLUE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:43 AM"
}, {
  "id": 496,
  "license_plate": "BK26",
  "plate_confidence": 90,
  "make": "HONDA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:44 AM"
}, {
  "id": 121,
  "license_plate": "H54",
  "plate_confidence": 91,
  "make": "INFINITI",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:58 AM"
}, {
  "id": 277,
  "license_plate": "Y75STN",
  "plate_confidence": 83,
  "make": "FORD",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:17 AM"
}, {
  "id": 17,
  "license_plate": "2",
  "plate_confidence": 88,
  "make": "CHEVROLET",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:41 AM"
}, {
  "id": 439,
  "license_plate": "B878ZS",
  "plate_confidence": 90,
  "make": "FORD",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:38 AM"
}, {
  "id": 46,
  "license_plate": "46DF20",
  "plate_confidence": 83,
  "make": "FORD",
  "color": "BLUE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:48 AM"
}, {
  "id": 361,
  "license_plate": "44AJKQ",
  "plate_confidence": 93,
  "make": "TOYOTA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:27 AM"
}, {
  "id": 81,
  "license_plate": "Q08",
  "plate_confidence": 82,
  "make": "FORD",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:52 AM"
}, {
  "id": 358,
  "license_plate": "1CAB48",
  "plate_confidence": 98,
  "make": "LANDROVER",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:27 AM"
}, {
  "id": 178,
  "license_plate": "09AJVY",
  "plate_confidence": 88,
  "make": "CHEVROLET",
  "color": "BLUE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:04 AM"
}, {
  "id": 5,
  "license_plate": "KXFV39",
  "plate_confidence": 94,
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:23 AM"
}, {
  "id": 477,
  "license_plate": "R8",
  "plate_confidence": 80,
  "make": "HONDA",
  "color": "BLUE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:42 AM"
}, {
  "id": 414,
  "license_plate": "TJ2562",
  "plate_confidence": 95,
  "make": "FORD",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:35 AM"
}, {
  "id": 95,
  "license_plate": "49",
  "plate_confidence": 77,
  "make": "TOYOTA",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:54 AM"
}, {
  "id": 288,
  "license_plate": "78AHD2",
  "plate_confidence": 90,
  "make": "DODGE",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:18 AM"
}, {
  "id": 295,
  "license_plate": "ASS31S",
  "plate_confidence": 91,
  "make": "FORD",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:19 AM"
}, {
  "id": 465,
  "license_plate": "72AUBJ",
  "plate_confidence": 93,
  "make": "DODGE",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:40 AM"
}, {
  "id": 156,
  "license_plate": "PLM7652",
  "plate_confidence": 97,
  "make": "GMC",
  "color": "RED",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:02 AM"
}, {
  "id": 372,
  "license_plate": "T268",
  "plate_confidence": 95,
  "make": "FORD",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:29 AM"
}, {
  "id": 197,
  "license_plate": "AK0L5HP",
  "plate_confidence": 89,
  "make": "TOYOTA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:07 AM"
}, {
  "id": 310,
  "license_plate": "37ABRW",
  "plate_confidence": 94,
  "make": "TOYOTA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:21 AM"
}, {
  "id": 497,
  "license_plate": "N60771",
  "plate_confidence": 92,
  "make": "DODGE",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:44 AM"
}, {
  "id": 167,
  "license_plate": "QDONN",
  "plate_confidence": 94,
  "make": "FORD",
  "color": "RED",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:03 AM"
}, {
  "id": 49,
  "license_plate": "87V",
  "plate_confidence": 91,
  "make": "VOLVO",
  "color": "RED",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:48 AM"
}, {
  "id": 481,
  "license_plate": "Y9925",
  "plate_confidence": 90,
  "make": "TOYOTA",
  "color": "BLUE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:42 AM"
}, {
  "id": 167,
  "license_plate": "QDONN",
  "plate_confidence": 94,
  "make": "FORD",
  "color": "RED",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:03 AM"
}, {
  "id": 83,
  "license_plate": "JR3",
  "plate_confidence": 88,
  "make": "BENTLEY",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:53 AM"
}, {
  "id": 87,
  "license_plate": "LFL025",
  "plate_confidence": 91,
  "make": "FORD",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:53 AM"
}, {
  "id": 7,
  "license_plate": "158KN",
  "plate_confidence": 87,
  "make": "MITSUBISHI",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:32 AM"
}, {
  "id": 362,
  "license_plate": "X0",
  "plate_confidence": 82,
  "make": "ALFAROMEO",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:28 AM"
}, {
  "id": 337,
  "license_plate": "AIH1SZ",
  "plate_confidence": 89,
  "make": "FORD",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:24 AM"
}, {
  "id": 394,
  "license_plate": "KKW60",
  "plate_confidence": 85,
  "make": "TOYOTA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:33 AM"
}, {
  "id": 141,
  "license_plate": "AE8F7",
  "plate_confidence": 89,
  "make": "JEEP",
  "color": "RED",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:01 AM"
}, {
  "id": 440,
  "license_plate": "HKD3788",
  "plate_confidence": 93,
  "make": "HYUNDAI",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:38 AM"
}, {
  "id": 137,
  "license_plate": "AS07NI",
  "plate_confidence": 92,
  "make": "CHEVROLET",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:00 AM"
}, {
  "id": 463,
  "license_plate": "NSX8175",
  "plate_confidence": 94,
  "make": "BMW",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:40 AM"
}, {
  "id": 196,
  "license_plate": "NT5M",
  "plate_confidence": 84,
  "make": "HONDA",
  "color": "RED",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:07 AM"
}, {
  "id": 485,
  "license_plate": "3S",
  "plate_confidence": 83,
  "make": "LEXUS",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:42 AM"
}, {
  "id": 162,
  "license_plate": "6K21J8",
  "plate_confidence": 84,
  "make": "NISSAN",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:03 AM"
}, {
  "id": 355,
  "license_plate": "IEZC",
  "plate_confidence": 88,
  "make": "LANDROVER",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:27 AM"
}, {
  "id": 86,
  "license_plate": "AJ12JI",
  "plate_confidence": 95,
  "make": "NISSAN",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:53 AM"
}, {
  "id": 81,
  "license_plate": "Q08",
  "plate_confidence": 82,
  "make": "FORD",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:52 AM"
}, {
  "id": 455,
  "license_plate": "96",
  "plate_confidence": 83,
  "make": "KIA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:40 AM"
}, {
  "id": 29,
  "license_plate": "AS",
  "plate_confidence": 80,
  "make": "FORD",
  "color": "BLUE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:43 AM"
}, {
  "id": 291,
  "license_plate": "KBT9326",
  "plate_confidence": 94,
  "make": "NISSAN",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:18 AM"
}, {
  "id": 250,
  "license_plate": "AI4IE",
  "plate_confidence": 89,
  "make": "MITSUBISHI",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:14 AM"
}, {
  "id": 260,
  "license_plate": "BPP6K",
  "plate_confidence": 95,
  "make": "GMC",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:16 AM"
}, {
  "id": 233,
  "license_plate": "12ZJ",
  "plate_confidence": 87,
  "make": "PORSCHE",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:12 AM"
}, {
  "id": 329,
  "license_plate": "LFW24",
  "plate_confidence": 93,
  "make": "FORD",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:24 AM"
}, {
  "id": 68,
  "license_plate": "21EK",
  "plate_confidence": 90,
  "make": "FORD",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:51 AM"
}, {
  "id": 150,
  "license_plate": "D1RH",
  "plate_confidence": 96,
  "make": "TOYOTA",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:01 AM"
}, {
  "id": 67,
  "license_plate": "CI00785",
  "plate_confidence": 89,
  "make": "DODGE",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:51 AM"
}, {
  "id": 269,
  "license_plate": "CTRT94",
  "plate_confidence": 85,
  "make": "DODGE",
  "color": "BLUE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:16 AM"
}, {
  "id": 241,
  "license_plate": "R480",
  "plate_confidence": 88,
  "make": "KIA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:13 AM"
}, {
  "id": 83,
  "license_plate": "JR3",
  "plate_confidence": 88,
  "make": "BENTLEY",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:53 AM"
}, {
  "id": 368,
  "license_plate": "39LGKD",
  "plate_confidence": 91,
  "make": "HONDA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:28 AM"
}, {
  "id": 221,
  "license_plate": "DC32XK",
  "plate_confidence": 85,
  "make": "NISSAN",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:10 AM"
}, {
  "id": 108,
  "license_plate": "PYSA25",
  "plate_confidence": 95,
  "make": "FORD",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:56 AM"
}, {
  "id": 108,
  "license_plate": "PYSA25",
  "plate_confidence": 95,
  "make": "FORD",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:56 AM"
}, {
  "id": 103,
  "license_plate": "IT08CZ",
  "plate_confidence": 89,
  "make": "LANDROVER",
  "color": "GREEN",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:54 AM"
}, {
  "id": 253,
  "license_plate": "54",
  "plate_confidence": 73,
  "make": "MAZDA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:15 AM"
}, {
  "id": 347,
  "license_plate": "WR0510",
  "plate_confidence": 87,
  "make": "TOYOTA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:26 AM"
}, {
  "id": 494,
  "license_plate": "QCNC10",
  "plate_confidence": 84,
  "make": "LANDROVER",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:44 AM"
}, {
  "id": 86,
  "license_plate": "AJ12JI",
  "plate_confidence": 95,
  "make": "NISSAN",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:53 AM"
}, {
  "id": 13,
  "license_plate": "RC",
  "plate_confidence": 77,
  "make": "TOYOTA",
  "color": "BLUE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:40 AM"
}, {
  "id": 387,
  "license_plate": "228JI",
  "plate_confidence": 90,
  "make": "GMC",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:31 AM"
}, {
  "id": 408,
  "license_plate": "PK0",
  "plate_confidence": 84,
  "make": "CHEVROLET",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:34 AM"
}, {
  "id": 62,
  "license_plate": "13E",
  "plate_confidence": 91,
  "make": "TOYOTA",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:50 AM"
}, {
  "id": 286,
  "license_plate": "NNC646",
  "plate_confidence": 96,
  "make": "MAZDA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:18 AM"
}, {
  "id": 271,
  "license_plate": "HCC38",
  "plate_confidence": 82,
  "make": "HUMMER",
  "color": "RED",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:16 AM"
}, {
  "id": 69,
  "license_plate": "ZBK19",
  "plate_confidence": 88,
  "make": "CHEVROLET",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:51 AM"
}, {
  "id": 119,
  "license_plate": "AH71JY",
  "plate_confidence": 89,
  "make": "JEEP",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:58 AM"
}, {
  "id": 64,
  "license_plate": "Y17HUA",
  "plate_confidence": 94,
  "make": "TOYOTA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:50 AM"
}, {
  "id": 212,
  "license_plate": "KW98",
  "plate_confidence": 85,
  "make": "NISSAN",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:09 AM"
}, {
  "id": 248,
  "license_plate": "KBB",
  "plate_confidence": 82,
  "make": "ALFAROMEO",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:13 AM"
}, {
  "id": 64,
  "license_plate": "Y17HUA",
  "plate_confidence": 94,
  "make": "TOYOTA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:50 AM"
}, {
  "id": 497,
  "license_plate": "N60771",
  "plate_confidence": 92,
  "make": "DODGE",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:44 AM"
}, {
  "id": 323,
  "license_plate": "CG4PY",
  "plate_confidence": 94,
  "make": "HONDA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:22 AM"
}, {
  "id": 35,
  "license_plate": "8V",
  "plate_confidence": 79,
  "make": "VOLKSWAGEN",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:45 AM"
}, {
  "id": 79,
  "license_plate": "IJ97R",
  "plate_confidence": 83,
  "make": "HONDA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:52 AM"
}, {
  "id": 397,
  "license_plate": "LVAA24",
  "plate_confidence": 87,
  "make": "VOLVO",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:33 AM"
}, {
  "id": 96,
  "license_plate": "K61RM",
  "plate_confidence": 93,
  "make": "AUDI",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:54 AM"
}, {
  "id": 317,
  "license_plate": "GT10P",
  "plate_confidence": 88,
  "make": "TOYOTA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:21 AM"
}, {
  "id": 354,
  "license_plate": "DE2PCH",
  "plate_confidence": 83,
  "make": "ISUZU",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:27 AM"
}, {
  "id": 335,
  "license_plate": "YZ006",
  "plate_confidence": 84,
  "make": "KIA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:24 AM"
}, {
  "id": 331,
  "license_plate": "DUB",
  "plate_confidence": 84,
  "make": "LANDROVER",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:24 AM"
}, {
  "id": 195,
  "license_plate": "2B8934",
  "plate_confidence": 88,
  "make": "VOLKSWAGEN",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:07 AM"
}, {
  "id": 197,
  "license_plate": "AK0L5HP",
  "plate_confidence": 89,
  "make": "TOYOTA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:07 AM"
}, {
  "id": 279,
  "license_plate": "EGT822",
  "plate_confidence": 96,
  "make": "NISSAN",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:17 AM"
}, {
  "id": 203,
  "license_plate": "C3RD",
  "plate_confidence": 92,
  "make": "HYUNDAI",
  "color": "BLUE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:09 AM"
}, {
  "id": 36,
  "license_plate": "DU5",
  "plate_confidence": 91,
  "make": "HONDA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:46 AM"
}, {
  "id": 71,
  "license_plate": "31Z",
  "plate_confidence": 79,
  "make": "HONDA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:51 AM"
}, {
  "id": 483,
  "license_plate": "765ECW",
  "plate_confidence": 94,
  "make": "MAZDA",
  "color": "RED",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:42 AM"
}, {
  "id": 109,
  "license_plate": "GX",
  "plate_confidence": 93,
  "make": "VOLVO",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:56 AM"
}, {
  "id": 481,
  "license_plate": "Y9925",
  "plate_confidence": 90,
  "make": "TOYOTA",
  "color": "BLUE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:42 AM"
}, {
  "id": 167,
  "license_plate": "QDONN",
  "plate_confidence": 94,
  "make": "FORD",
  "color": "RED",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:03 AM"
}, {
  "id": 83,
  "license_plate": "JR3",
  "plate_confidence": 88,
  "make": "BENTLEY",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:53 AM"
}, {
  "id": 87,
  "license_plate": "LFL025",
  "plate_confidence": 91,
  "make": "FORD",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:53 AM"
}, {
  "id": 7,
  "license_plate": "158KN",
  "plate_confidence": 87,
  "make": "MITSUBISHI",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:32 AM"
}, {
  "id": 362,
  "license_plate": "X0",
  "plate_confidence": 82,
  "make": "ALFAROMEO",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:28 AM"
}, {
  "id": 337,
  "license_plate": "AIH1SZ",
  "plate_confidence": 89,
  "make": "FORD",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:24 AM"
}, {
  "id": 394,
  "license_plate": "KKW60",
  "plate_confidence": 85,
  "make": "TOYOTA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:33 AM"
}, {
  "id": 141,
  "license_plate": "AE8F7",
  "plate_confidence": 89,
  "make": "JEEP",
  "color": "RED",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:01 AM"
}, {
  "id": 440,
  "license_plate": "HKD3788",
  "plate_confidence": 93,
  "make": "HYUNDAI",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:38 AM"
}, {
  "id": 137,
  "license_plate": "AS07NI",
  "plate_confidence": 92,
  "make": "CHEVROLET",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:00 AM"
}, {
  "id": 463,
  "license_plate": "NSX8175",
  "plate_confidence": 94,
  "make": "BMW",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:40 AM"
}, {
  "id": 196,
  "license_plate": "NT5M",
  "plate_confidence": 84,
  "make": "HONDA",
  "color": "RED",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:07 AM"
}, {
  "id": 485,
  "license_plate": "3S",
  "plate_confidence": 83,
  "make": "LEXUS",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:42 AM"
}, {
  "id": 162,
  "license_plate": "6K21J8",
  "plate_confidence": 84,
  "make": "NISSAN",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:03 AM"
}, {
  "id": 355,
  "license_plate": "IEZC",
  "plate_confidence": 88,
  "make": "LANDROVER",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:27 AM"
}, {
  "id": 86,
  "license_plate": "AJ12JI",
  "plate_confidence": 95,
  "make": "NISSAN",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:53 AM"
}, {
  "id": 81,
  "license_plate": "Q08",
  "plate_confidence": 82,
  "make": "FORD",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:52 AM"
}, {
  "id": 455,
  "license_plate": "96",
  "plate_confidence": 83,
  "make": "KIA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:40 AM"
}, {
  "id": 29,
  "license_plate": "AS",
  "plate_confidence": 80,
  "make": "FORD",
  "color": "BLUE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:43 AM"
}, {
  "id": 291,
  "license_plate": "KBT9326",
  "plate_confidence": 94,
  "make": "NISSAN",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:18 AM"
}, {
  "id": 250,
  "license_plate": "AI4IE",
  "plate_confidence": 89,
  "make": "MITSUBISHI",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:14 AM"
}, {
  "id": 260,
  "license_plate": "BPP6K",
  "plate_confidence": 95,
  "make": "GMC",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:16 AM"
}, {
  "id": 233,
  "license_plate": "12ZJ",
  "plate_confidence": 87,
  "make": "PORSCHE",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:12 AM"
}, {
  "id": 329,
  "license_plate": "LFW24",
  "plate_confidence": 93,
  "make": "FORD",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:24 AM"
}, {
  "id": 68,
  "license_plate": "21EK",
  "plate_confidence": 90,
  "make": "FORD",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:51 AM"
}, {
  "id": 150,
  "license_plate": "D1RH",
  "plate_confidence": 96,
  "make": "TOYOTA",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:01 AM"
}, {
  "id": 67,
  "license_plate": "CI00785",
  "plate_confidence": 89,
  "make": "DODGE",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:51 AM"
}, {
  "id": 269,
  "license_plate": "CTRT94",
  "plate_confidence": 85,
  "make": "DODGE",
  "color": "BLUE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:16 AM"
}, {
  "id": 241,
  "license_plate": "R480",
  "plate_confidence": 88,
  "make": "KIA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:13 AM"
}, {
  "id": 83,
  "license_plate": "JR3",
  "plate_confidence": 88,
  "make": "BENTLEY",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:53 AM"
}, {
  "id": 368,
  "license_plate": "39LGKD",
  "plate_confidence": 91,
  "make": "HONDA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:28 AM"
}, {
  "id": 221,
  "license_plate": "DC32XK",
  "plate_confidence": 85,
  "make": "NISSAN",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:10 AM"
}, {
  "id": 108,
  "license_plate": "PYSA25",
  "plate_confidence": 95,
  "make": "FORD",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:56 AM"
}, {
  "id": 108,
  "license_plate": "PYSA25",
  "plate_confidence": 95,
  "make": "FORD",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:56 AM"
}, {
  "id": 103,
  "license_plate": "IT08CZ",
  "plate_confidence": 89,
  "make": "LANDROVER",
  "color": "GREEN",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:54 AM"
}, {
  "id": 253,
  "license_plate": "54",
  "plate_confidence": 73,
  "make": "MAZDA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:15 AM"
}, {
  "id": 347,
  "license_plate": "WR0510",
  "plate_confidence": 87,
  "make": "TOYOTA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:26 AM"
}, {
  "id": 494,
  "license_plate": "QCNC10",
  "plate_confidence": 84,
  "make": "LANDROVER",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:44 AM"
}, {
  "id": 86,
  "license_plate": "AJ12JI",
  "plate_confidence": 95,
  "make": "NISSAN",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:53 AM"
}, {
  "id": 13,
  "license_plate": "RC",
  "plate_confidence": 77,
  "make": "TOYOTA",
  "color": "BLUE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:40 AM"
}, {
  "id": 387,
  "license_plate": "228JI",
  "plate_confidence": 90,
  "make": "GMC",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:31 AM"
}, {
  "id": 408,
  "license_plate": "PK0",
  "plate_confidence": 84,
  "make": "CHEVROLET",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:34 AM"
}, {
  "id": 62,
  "license_plate": "13E",
  "plate_confidence": 91,
  "make": "TOYOTA",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:50 AM"
}, {
  "id": 286,
  "license_plate": "NNC646",
  "plate_confidence": 96,
  "make": "MAZDA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:18 AM"
}, {
  "id": 271,
  "license_plate": "HCC38",
  "plate_confidence": 82,
  "make": "HUMMER",
  "color": "RED",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:16 AM"
}, {
  "id": 69,
  "license_plate": "ZBK19",
  "plate_confidence": 88,
  "make": "CHEVROLET",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:51 AM"
}, {
  "id": 119,
  "license_plate": "AH71JY",
  "plate_confidence": 89,
  "make": "JEEP",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:58 AM"
}, {
  "id": 64,
  "license_plate": "Y17HUA",
  "plate_confidence": 94,
  "make": "TOYOTA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:50 AM"
}, {
  "id": 212,
  "license_plate": "KW98",
  "plate_confidence": 85,
  "make": "NISSAN",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:09 AM"
}, {
  "id": 248,
  "license_plate": "KBB",
  "plate_confidence": 82,
  "make": "ALFAROMEO",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:13 AM"
}, {
  "id": 64,
  "license_plate": "Y17HUA",
  "plate_confidence": 94,
  "make": "TOYOTA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:50 AM"
}, {
  "id": 497,
  "license_plate": "N60771",
  "plate_confidence": 92,
  "make": "DODGE",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:44 AM"
}, {
  "id": 323,
  "license_plate": "CG4PY",
  "plate_confidence": 94,
  "make": "HONDA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:22 AM"
}, {
  "id": 35,
  "license_plate": "8V",
  "plate_confidence": 79,
  "make": "VOLKSWAGEN",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:45 AM"
}, {
  "id": 79,
  "license_plate": "IJ97R",
  "plate_confidence": 83,
  "make": "HONDA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:52 AM"
}, {
  "id": 397,
  "license_plate": "LVAA24",
  "plate_confidence": 87,
  "make": "VOLVO",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:33 AM"
}, {
  "id": 96,
  "license_plate": "K61RM",
  "plate_confidence": 93,
  "make": "AUDI",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:54 AM"
}, {
  "id": 317,
  "license_plate": "GT10P",
  "plate_confidence": 88,
  "make": "TOYOTA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:21 AM"
}, {
  "id": 354,
  "license_plate": "DE2PCH",
  "plate_confidence": 83,
  "make": "ISUZU",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:27 AM"
}, {
  "id": 335,
  "license_plate": "YZ006",
  "plate_confidence": 84,
  "make": "KIA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:24 AM"
}, {
  "id": 331,
  "license_plate": "DUB",
  "plate_confidence": 84,
  "make": "LANDROVER",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:24 AM"
}, {
  "id": 195,
  "license_plate": "2B8934",
  "plate_confidence": 88,
  "make": "VOLKSWAGEN",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:07 AM"
}, {
  "id": 197,
  "license_plate": "AK0L5HP",
  "plate_confidence": 89,
  "make": "TOYOTA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:07 AM"
}, {
  "id": 279,
  "license_plate": "EGT822",
  "plate_confidence": 96,
  "make": "NISSAN",
  "color": "WHITE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:17 AM"
}, {
  "id": 203,
  "license_plate": "C3RD",
  "plate_confidence": 92,
  "make": "HYUNDAI",
  "color": "BLUE",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:09 AM"
}, {
  "id": 36,
  "license_plate": "DU5",
  "plate_confidence": 91,
  "make": "HONDA",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:46 AM"
}, {
  "id": 71,
  "license_plate": "31Z",
  "plate_confidence": 79,
  "make": "HONDA",
  "color": "SILVER_GRAY",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:51 AM"
}, {
  "id": 483,
  "license_plate": "765ECW",
  "plate_confidence": 94,
  "make": "MAZDA",
  "color": "RED",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "7:42 AM"
}, {
  "id": 109,
  "license_plate": "GX",
  "plate_confidence": 93,
  "make": "VOLVO",
  "color": "BLACK",
  "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
  "loc_address": "9340 6 mile Cypress Parkway",
  "loc_state": "FL",
  "loc_zip": 33966,
  "date": "4/6/2023",
  "time": "6:56 AM"
}]