export const data = 
[
    {
        "#": "1",
        "Time": "4/6/2023 6:22",
        "license_plate": "FLN",
        "plate_confidence": "83",
        "Name": "",
        "Jurisdiction": "TN",
        "Jurisdiction Confidence": "50",
        "make": "",
        "color": "",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/6/2023",
        "time": "6:22 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "10",
        "Time": "4/6/2023 6:38",
        "license_plate": "E135860",
        "plate_confidence": "86",
        "Name": "",
        "Jurisdiction": "IL",
        "Jurisdiction Confidence": "84",
        "make": "SUZUKI",
        "color": "BLUE",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/6/2023",
        "time": "6:38 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "40",
        "Time": "4/6/2023 6:46",
        "license_plate": "LTWGL92",
        "plate_confidence": "85",
        "Name": "",
        "Jurisdiction": "AZ",
        "Jurisdiction Confidence": "63",
        "make": "GMC",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/6/2023",
        "time": "6:46 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "70",
        "Time": "4/6/2023 6:51",
        "license_plate": "HNBO",
        "plate_confidence": "79",
        "Name": "",
        "Jurisdiction": "IL",
        "Jurisdiction Confidence": "68",
        "make": "FORD",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/6/2023",
        "time": "6:51 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "100",
        "Time": "4/6/2023 6:54",
        "license_plate": "12P",
        "plate_confidence": "92",
        "Name": "",
        "Jurisdiction": "TN",
        "Jurisdiction Confidence": "98",
        "make": "FORD",
        "color": "SILVER_GRAY",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/6/2023",
        "time": "6:54 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "400",
        "Time": "4/6/2023 7:33",
        "license_plate": "NJNOY",
        "plate_confidence": "88",
        "Name": "",
        "Jurisdiction": "AL",
        "Jurisdiction Confidence": "61",
        "make": "DODGE",
        "color": "BLUE",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/6/2023",
        "time": "7:33 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "700",
        "Time": "4/6/2023 8:12",
        "license_plate": "BLU60",
        "plate_confidence": "94",
        "Name": "",
        "Jurisdiction": "IL",
        "Jurisdiction Confidence": "50",
        "make": "ALFAROMEO",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/6/2023",
        "time": "8:12 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "1000",
        "Time": "4/6/2023 8:50",
        "license_plate": "700LH",
        "plate_confidence": "94",
        "Name": "",
        "Jurisdiction": "NC",
        "Jurisdiction Confidence": "29",
        "make": "DODGE",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/6/2023",
        "time": "8:50 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "4000",
        "Time": "4/6/2023 15:29",
        "license_plate": "F7",
        "plate_confidence": "78",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "98",
        "make": "HONDA",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/6/2023",
        "time": "3:29 PM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "1",
        "Time": "4/7/2023 6:12",
        "license_plate": "40",
        "plate_confidence": "87",
        "Name": "",
        "Jurisdiction": "MA",
        "Jurisdiction Confidence": "87",
        "make": "",
        "color": "",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/7/2023",
        "time": "6:12 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "10",
        "Time": "4/7/2023 6:38",
        "license_plate": "94",
        "plate_confidence": "80",
        "Name": "",
        "Jurisdiction": "IL",
        "Jurisdiction Confidence": "73",
        "make": "FORD",
        "color": "SILVER_GRAY",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/7/2023",
        "time": "6:38 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "40",
        "Time": "4/7/2023 6:51",
        "license_plate": "0GD",
        "plate_confidence": "82",
        "Name": "",
        "Jurisdiction": "IL",
        "Jurisdiction Confidence": "51",
        "make": "VOLVO",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/7/2023",
        "time": "6:51 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "70",
        "Time": "4/7/2023 6:55",
        "license_plate": "Y13CY",
        "plate_confidence": "84",
        "Name": "",
        "Jurisdiction": "IL",
        "Jurisdiction Confidence": "44",
        "make": "CHEVROLET",
        "color": "BLUE",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/7/2023",
        "time": "6:55 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "100",
        "Time": "4/7/2023 7:01",
        "license_plate": "220H7",
        "plate_confidence": "92",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "98",
        "make": "MITSUBISHI",
        "color": "SILVER_GRAY",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/7/2023",
        "time": "7:01 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "400",
        "Time": "4/7/2023 7:52",
        "license_plate": "XD42B3",
        "plate_confidence": "83",
        "Name": "",
        "Jurisdiction": "KY",
        "Jurisdiction Confidence": "75",
        "make": "FORD",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/7/2023",
        "time": "7:52 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "700",
        "Time": "4/7/2023 8:28",
        "license_plate": "Z6CR",
        "plate_confidence": "81",
        "Name": "",
        "Jurisdiction": "VT",
        "Jurisdiction Confidence": "40",
        "make": "HONDA",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/7/2023",
        "time": "8:28 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "1000",
        "Time": "4/7/2023 9:05",
        "license_plate": "D0",
        "plate_confidence": "73",
        "Name": "",
        "Jurisdiction": "IL",
        "Jurisdiction Confidence": "75",
        "make": "VOLKSWAGEN",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/7/2023",
        "time": "9:05 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "4000",
        "Time": "4/7/2023 15:43",
        "license_plate": "43DDNH",
        "plate_confidence": "93",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "99",
        "make": "HONDA",
        "color": "SILVER_GRAY",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/7/2023",
        "time": "3:43 PM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "1",
        "Time": "4/8/2023 5:53",
        "license_plate": "88",
        "plate_confidence": "71",
        "Name": "",
        "Jurisdiction": "TX",
        "Jurisdiction Confidence": "52",
        "make": "",
        "color": "",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/8/2023",
        "time": "5:53 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "10",
        "Time": "4/8/2023 6:22",
        "license_plate": "JS",
        "plate_confidence": "83",
        "Name": "",
        "Jurisdiction": "IL",
        "Jurisdiction Confidence": "83",
        "make": "",
        "color": "",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/8/2023",
        "time": "6:22 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "40",
        "Time": "4/8/2023 6:43",
        "license_plate": "57BX22",
        "plate_confidence": "92",
        "Name": "",
        "Jurisdiction": "IL",
        "Jurisdiction Confidence": "44",
        "make": "TOYOTA",
        "color": "SILVER_GRAY",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/8/2023",
        "time": "6:43 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "70",
        "Time": "4/8/2023 6:49",
        "license_plate": "P705",
        "plate_confidence": "89",
        "Name": "",
        "Jurisdiction": "MA",
        "Jurisdiction Confidence": "55",
        "make": "VOLVO",
        "color": "SILVER_GRAY",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/8/2023",
        "time": "6:49 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "100",
        "Time": "4/8/2023 6:57",
        "license_plate": "77PDZ",
        "plate_confidence": "94",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "96",
        "make": "MITSUBISHI",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/8/2023",
        "time": "6:57 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "400",
        "Time": "4/8/2023 7:48",
        "license_plate": "AS98TB",
        "plate_confidence": "90",
        "Name": "",
        "Jurisdiction": "VT",
        "Jurisdiction Confidence": "49",
        "make": "NISSAN",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/8/2023",
        "time": "7:48 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "700",
        "Time": "4/8/2023 8:33",
        "license_plate": "8916N",
        "plate_confidence": "78",
        "Name": "",
        "Jurisdiction": "IL",
        "Jurisdiction Confidence": "51",
        "make": "ISUZU",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/8/2023",
        "time": "8:33 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "1000",
        "Time": "4/8/2023 9:08",
        "license_plate": "TJET",
        "plate_confidence": "83",
        "Name": "",
        "Jurisdiction": "CA",
        "Jurisdiction Confidence": "33",
        "make": "MITSUBISHI",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/8/2023",
        "time": "9:08 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "4000",
        "Time": "4/8/2023 14:38",
        "license_plate": "JKDYJ6",
        "plate_confidence": "93",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "100",
        "make": "JAGUAR",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/8/2023",
        "time": "2:38 PM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "1",
        "Time": "4/9/2023 6:21",
        "license_plate": "31",
        "plate_confidence": "77",
        "Name": "",
        "Jurisdiction": "IL",
        "Jurisdiction Confidence": "74",
        "make": "",
        "color": "",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/9/2023",
        "time": "6:21 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "10",
        "Time": "4/9/2023 7:00",
        "license_plate": "57M",
        "plate_confidence": "86",
        "Name": "",
        "Jurisdiction": "IL",
        "Jurisdiction Confidence": "63",
        "make": "TOYOTA",
        "color": "SILVER_GRAY",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/9/2023",
        "time": "7:00 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "40",
        "Time": "4/9/2023 7:12",
        "license_plate": "LKWX13",
        "plate_confidence": "89",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "97",
        "make": "NISSAN",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/9/2023",
        "time": "7:12 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "70",
        "Time": "4/9/2023 7:18",
        "license_plate": "QLVK27",
        "plate_confidence": "93",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "100",
        "make": "NISSAN",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/9/2023",
        "time": "7:18 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "100",
        "Time": "4/9/2023 7:24",
        "license_plate": "726J",
        "plate_confidence": "80",
        "Name": "",
        "Jurisdiction": "KY",
        "Jurisdiction Confidence": "61",
        "make": "JEEP",
        "color": "RED",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/9/2023",
        "time": "7:24 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "400",
        "Time": "4/9/2023 8:28",
        "license_plate": "54A",
        "plate_confidence": "85",
        "Name": "",
        "Jurisdiction": "IL",
        "Jurisdiction Confidence": "47",
        "make": "FORD",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/9/2023",
        "time": "8:28 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "700",
        "Time": "4/9/2023 9:54",
        "license_plate": "0RJA73",
        "plate_confidence": "85",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "67",
        "make": "FORD",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/9/2023",
        "time": "9:54 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "1000",
        "Time": "4/9/2023 10:47",
        "license_plate": "698PE",
        "plate_confidence": "83",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "99",
        "make": "TOYOTA",
        "color": "SILVER_GRAY",
        "List": "",
        "Location": "CLV 560A",
        "Comments": "",
        "date": "4/9/2023",
        "time": "10:47 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "1",
        "Time": "4/6/2023 4:52",
        "license_plate": "10",
        "plate_confidence": "84",
        "Name": "",
        "Jurisdiction": "UT",
        "Jurisdiction Confidence": "54",
        "make": "",
        "color": "",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/6/2023",
        "time": "4:52 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "10",
        "Time": "4/6/2023 6:40",
        "license_plate": "2380AT",
        "plate_confidence": "96",
        "Name": "",
        "Jurisdiction": "IL",
        "Jurisdiction Confidence": "97",
        "make": "SUBARU",
        "color": "RED",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/6/2023",
        "time": "6:40 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "40",
        "Time": "4/6/2023 6:44",
        "license_plate": "QTPV18",
        "plate_confidence": "97",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "89",
        "make": "TOYOTA",
        "color": "SILVER_GRAY",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/6/2023",
        "time": "6:44 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "70",
        "Time": "4/6/2023 6:48",
        "license_plate": "51ZPP",
        "plate_confidence": "95",
        "Name": "",
        "Jurisdiction": "IL",
        "Jurisdiction Confidence": "47",
        "make": "...",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/6/2023",
        "time": "6:48 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "100",
        "Time": "4/6/2023 6:52",
        "license_plate": "56000X",
        "plate_confidence": "98",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "65",
        "make": "CHEVROLET",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/6/2023",
        "time": "6:52 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "400",
        "Time": "4/6/2023 7:24",
        "license_plate": "QYLI89",
        "plate_confidence": "97",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "100",
        "make": "TOYOTA",
        "color": "SILVER_GRAY",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/6/2023",
        "time": "7:24 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "700",
        "Time": "4/6/2023 8:00",
        "license_plate": "LZLP4",
        "plate_confidence": "97",
        "Name": "",
        "Jurisdiction": "IL",
        "Jurisdiction Confidence": "69",
        "make": "FORD",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/6/2023",
        "time": "8:00 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "1000",
        "Time": "4/6/2023 8:41",
        "license_plate": "C15VT",
        "plate_confidence": "98",
        "Name": "",
        "Jurisdiction": "UT",
        "Jurisdiction Confidence": "45",
        "make": "FORD",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/6/2023",
        "time": "8:41 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "4000",
        "Time": "4/6/2023 16:08",
        "license_plate": "10DFZB",
        "plate_confidence": "98",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "81",
        "make": "FORD",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/6/2023",
        "time": "4:08 PM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "1",
        "Time": "4/7/2023 5:07",
        "license_plate": "1V",
        "plate_confidence": "80",
        "Name": "",
        "Jurisdiction": "OR",
        "Jurisdiction Confidence": "86",
        "make": "...",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/7/2023",
        "time": "5:07 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "10",
        "Time": "4/7/2023 6:21",
        "license_plate": "02U5934",
        "plate_confidence": "86",
        "Name": "",
        "Jurisdiction": "TN",
        "Jurisdiction Confidence": "66",
        "make": "FORD",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/7/2023",
        "time": "6:21 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "40",
        "Time": "4/7/2023 6:29",
        "license_plate": "295",
        "plate_confidence": "80",
        "Name": "",
        "Jurisdiction": "MA",
        "Jurisdiction Confidence": "63",
        "make": "VOLKSWAGEN",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/7/2023",
        "time": "6:29 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "70",
        "Time": "4/7/2023 6:32",
        "license_plate": "Y624",
        "plate_confidence": "84",
        "Name": "",
        "Jurisdiction": "IL",
        "Jurisdiction Confidence": "81",
        "make": "...",
        "color": "SILVER_GRAY",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/7/2023",
        "time": "6:32 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "100",
        "Time": "4/7/2023 6:35",
        "license_plate": "91BLVKB",
        "plate_confidence": "93",
        "Name": "",
        "Jurisdiction": "SC",
        "Jurisdiction Confidence": "85",
        "make": "...",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/7/2023",
        "time": "6:35 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "400",
        "Time": "4/7/2023 7:15",
        "license_plate": "7VACDZB",
        "plate_confidence": "89",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "99",
        "make": "...",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/7/2023",
        "time": "7:15 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "700",
        "Time": "4/7/2023 7:56",
        "license_plate": "94AL9I",
        "plate_confidence": "94",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "99",
        "make": "KIA",
        "color": "YELLOW",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/7/2023",
        "time": "7:56 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "1000",
        "Time": "4/7/2023 8:38",
        "license_plate": "NCKCN27",
        "plate_confidence": "95",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "100",
        "make": "TOYOTA",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/7/2023",
        "time": "8:38 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "4000",
        "Time": "4/7/2023 15:31",
        "license_plate": "60AUBH",
        "plate_confidence": "99",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "100",
        "make": "NISSAN",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/7/2023",
        "time": "3:31 PM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "1",
        "Time": "4/8/2023 5:08",
        "license_plate": "10",
        "plate_confidence": "77",
        "Name": "",
        "Jurisdiction": "MA",
        "Jurisdiction Confidence": "39",
        "make": "DODGE",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/8/2023",
        "time": "5:08 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "10",
        "Time": "4/8/2023 6:25",
        "license_plate": "CX1",
        "plate_confidence": "85",
        "Name": "",
        "Jurisdiction": "LA",
        "Jurisdiction Confidence": "49",
        "make": "HONDA",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/8/2023",
        "time": "6:25 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "40",
        "Time": "4/8/2023 6:37",
        "license_plate": "QTBX56",
        "plate_confidence": "96",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "95",
        "make": "HONDA",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/8/2023",
        "time": "6:37 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "70",
        "Time": "4/8/2023 6:43",
        "license_plate": "85BML0",
        "plate_confidence": "95",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "67",
        "make": "...",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/8/2023",
        "time": "6:43 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "100",
        "Time": "4/8/2023 6:53",
        "license_plate": "581EE",
        "plate_confidence": "95",
        "Name": "",
        "Jurisdiction": "TMP",
        "Jurisdiction Confidence": "55",
        "make": "TOYOTA",
        "color": "SILVER_GRAY",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/8/2023",
        "time": "6:53 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "400",
        "Time": "4/8/2023 7:58",
        "license_plate": "IG36GM",
        "plate_confidence": "98",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "100",
        "make": "JEEP",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/8/2023",
        "time": "7:58 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "700",
        "Time": "4/8/2023 8:48",
        "license_plate": "AW02XN",
        "plate_confidence": "95",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "100",
        "make": "...",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/8/2023",
        "time": "8:48 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "1000",
        "Time": "4/8/2023 9:27",
        "license_plate": "SHP9987",
        "plate_confidence": "94",
        "Name": "",
        "Jurisdiction": "TX",
        "Jurisdiction Confidence": "100",
        "make": "MAZDA",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/8/2023",
        "time": "9:27 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "4000",
        "Time": "4/8/2023 16:11",
        "license_plate": "96DDMR",
        "plate_confidence": "94",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "97",
        "make": "...",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/8/2023",
        "time": "4:11 PM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "1",
        "Time": "4/9/2023 5:23",
        "license_plate": "18",
        "plate_confidence": "70",
        "Name": "",
        "Jurisdiction": "CA",
        "Jurisdiction Confidence": "43",
        "make": "...",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/9/2023",
        "time": "5:23 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "10",
        "Time": "4/9/2023 6:48",
        "license_plate": "422",
        "plate_confidence": "91",
        "Name": "",
        "Jurisdiction": "IL",
        "Jurisdiction Confidence": "74",
        "make": "HONDA",
        "color": "SILVER_GRAY",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/9/2023",
        "time": "6:48 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "40",
        "Time": "4/9/2023 7:03",
        "license_plate": "EQ1H44",
        "plate_confidence": "95",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "99",
        "make": "TOYOTA",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/9/2023",
        "time": "7:03 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "70",
        "Time": "4/9/2023 7:16",
        "license_plate": "1A122A2",
        "plate_confidence": "99",
        "Name": "",
        "Jurisdiction": "AL",
        "Jurisdiction Confidence": "100",
        "make": "NISSAN",
        "color": "SILVER_GRAY",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/9/2023",
        "time": "7:16 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "100",
        "Time": "4/9/2023 7:26",
        "license_plate": "QLKN41",
        "plate_confidence": "99",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "100",
        "make": "HONDA",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/9/2023",
        "time": "7:26 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "400",
        "Time": "4/9/2023 8:32",
        "license_plate": "8620DP",
        "plate_confidence": "89",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "94",
        "make": "CHEVROLET",
        "color": "SILVER_GRAY",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/9/2023",
        "time": "8:32 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "700",
        "Time": "4/9/2023 9:25",
        "license_plate": "B179AS",
        "plate_confidence": "98",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "99",
        "make": "GMC",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/9/2023",
        "time": "9:25 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "1000",
        "Time": "4/9/2023 10:13",
        "license_plate": "YX",
        "plate_confidence": "81",
        "Name": "",
        "Jurisdiction": "VT",
        "Jurisdiction Confidence": "64",
        "make": "TOYOTA",
        "color": "SILVER_GRAY",
        "List": "",
        "Location": "CLV 560B",
        "Comments": "",
        "date": "4/9/2023",
        "time": "10:13 AM",
        "loc_name": "Culvers - Ft. Myers - Cypress Pkwy",
        "loc_address": "9340 6 mile Cypress Parkway",
        "Loc. City": "Ft. Myers ",
        "loc_state": "FL",
        "loc_zip": "33966"
    },
    {
        "#": "1",
        "Time": "4/2/2023 0:20",
        "license_plate": "4CDBQ",
        "plate_confidence": "98",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "100",
        "make": "",
        "color": "",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/2/2023",
        "time": "12:20 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "10",
        "Time": "4/2/2023 5:09",
        "license_plate": "KPUI61",
        "plate_confidence": "98",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "100",
        "make": "",
        "color": "",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/2/2023",
        "time": "5:09 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "40",
        "Time": "4/2/2023 6:09",
        "license_plate": "IT79PN",
        "plate_confidence": "98",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "100",
        "make": "",
        "color": "",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/2/2023",
        "time": "6:09 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "70",
        "Time": "4/2/2023 6:31",
        "license_plate": "IT32UY",
        "plate_confidence": "98",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "99",
        "make": "FORD",
        "color": "BROWN",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/2/2023",
        "time": "6:31 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "100",
        "Time": "4/2/2023 6:51",
        "license_plate": "DLCF2R",
        "plate_confidence": "96",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "100",
        "make": "FORD",
        "color": "YELLOW",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/2/2023",
        "time": "6:51 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "400",
        "Time": "4/2/2023 8:32",
        "license_plate": "II50LA",
        "plate_confidence": "99",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "100",
        "make": "...",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/2/2023",
        "time": "8:32 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "700",
        "Time": "4/2/2023 9:39",
        "license_plate": "60GTU",
        "plate_confidence": "99",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "95",
        "make": "...",
        "color": "GREEN",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/2/2023",
        "time": "9:39 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "1000",
        "Time": "4/2/2023 10:28",
        "license_plate": "HSIQ49",
        "plate_confidence": "98",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "74",
        "make": "NISSAN",
        "color": "WHITE",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/2/2023",
        "time": "10:28 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "1",
        "Time": "4/3/2023 0:42",
        "license_plate": "IX00VM",
        "plate_confidence": "98",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "100",
        "make": "",
        "color": "",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/3/2023",
        "time": "12:42 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "10",
        "Time": "4/3/2023 3:42",
        "license_plate": "II17HI",
        "plate_confidence": "98",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "99",
        "make": "",
        "color": "",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/3/2023",
        "time": "3:42 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "40",
        "Time": "4/3/2023 5:08",
        "license_plate": "SAFNWRM",
        "plate_confidence": "99",
        "Name": "",
        "Jurisdiction": "PA",
        "Jurisdiction Confidence": "83",
        "make": "",
        "color": "",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/3/2023",
        "time": "5:08 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "70",
        "Time": "4/3/2023 5:41",
        "license_plate": "8Q3UCA",
        "plate_confidence": "94",
        "Name": "",
        "Jurisdiction": "MI",
        "Jurisdiction Confidence": "51",
        "make": "",
        "color": "",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/3/2023",
        "time": "5:41 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "100",
        "Time": "4/3/2023 6:05",
        "license_plate": "PEMZ79",
        "plate_confidence": "97",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "100",
        "make": "",
        "color": "",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/3/2023",
        "time": "6:05 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "400",
        "Time": "4/3/2023 7:56",
        "license_plate": "HCR8488",
        "plate_confidence": "99",
        "Name": "",
        "Jurisdiction": "OH",
        "Jurisdiction Confidence": "100",
        "make": "DODGE",
        "color": "RED",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/3/2023",
        "time": "7:56 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "700",
        "Time": "4/3/2023 9:02",
        "license_plate": "IW78DU",
        "plate_confidence": "98",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "100",
        "make": "HONDA",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/3/2023",
        "time": "9:02 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "1000",
        "Time": "4/3/2023 10:01",
        "license_plate": "1DR043",
        "plate_confidence": "98",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "99",
        "make": "NISSAN",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/3/2023",
        "time": "10:01 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "1",
        "Time": "4/4/2023 0:01",
        "license_plate": "QNKV64",
        "plate_confidence": "96",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "100",
        "make": "",
        "color": "",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/4/2023",
        "time": "12:01 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "10",
        "Time": "4/4/2023 3:37",
        "license_plate": "QBPOQ",
        "plate_confidence": "99",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "96",
        "make": "",
        "color": "",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/4/2023",
        "time": "3:37 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "40",
        "Time": "4/4/2023 4:58",
        "license_plate": "J02290",
        "plate_confidence": "98",
        "Name": "",
        "Jurisdiction": "NY",
        "Jurisdiction Confidence": "100",
        "make": "",
        "color": "",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/4/2023",
        "time": "4:58 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "70",
        "Time": "4/4/2023 5:40",
        "license_plate": "2647386",
        "plate_confidence": "98",
        "Name": "",
        "Jurisdiction": "CA",
        "Jurisdiction Confidence": "90",
        "make": "",
        "color": "",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/4/2023",
        "time": "5:40 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "100",
        "Time": "4/4/2023 5:59",
        "license_plate": "9415XS",
        "plate_confidence": "98",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "99",
        "make": "",
        "color": "",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/4/2023",
        "time": "5:59 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "400",
        "Time": "4/4/2023 7:43",
        "license_plate": "DU1810",
        "plate_confidence": "98",
        "Name": "",
        "Jurisdiction": "TMP",
        "Jurisdiction Confidence": "73",
        "make": "CHEVROLET",
        "color": "BLACK",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/4/2023",
        "time": "7:43 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    },
    {
        "#": "700",
        "Time": "4/4/2023 8:52",
        "license_plate": "GQAA04",
        "plate_confidence": "99",
        "Name": "",
        "Jurisdiction": "FL",
        "Jurisdiction Confidence": "97",
        "make": "DODGE",
        "color": "SILVER_GRAY",
        "List": "",
        "Location": "CLV 831A",
        "Comments": "",
        "date": "4/4/2023",
        "time": "8:52 AM",
        "loc_name": "Culvers - Cape Coral - Skyline Blvd",
        "loc_address": "2526 Skyline Blvd",
        "Loc. City": "Cape Coral",
        "loc_state": "FL",
        "loc_zip": "33914"
    }
]